# 参考 `application-example.yaml` 并在处添加订阅规则，请注意缩进
# Refer to `application-example.yaml` and add subscription rules there，please note the indentation

application:
  config:
    domain-detect:
      enable: false
      timeout: 10

  rule:
    remote:
      - name: AdGuard 基础过滤器
        path: https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_2_Base/filter.txt
        type: easylist

      - name: AWAvenue-Adblock-Rule
        path: https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/AWAvenue-Ads-Rule.txt
        type: easylist

      - name: xndeye web-ad-rule
        path: https://raw.githubusercontent.com/xndeye/web-ad-rule/master/easylist.txt
        type: easylist

      - name: xinggsf movie
        path: https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/mv.txt

      - name: damengzhu jiekouAD
        path: https://raw.githubusercontent.com/damengzhu/banad/main/jiekouAD.txt

      - name: cjxlist annoyance
        path: https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-annoyance.txt

      - name: ABP filters
        path: https://easylist-downloads.adblockplus.org/antiadblockfilters.txt

      - name: ABP 反广告过滤
        path: https://easylist-downloads.adblockplus.org/abp-filters-anti-cv.txt

      - name: uBlockOrigin privacy
        path: https://raw.githubusercontent.com/uBlockOrigin/uAssets/refs/heads/master/filters/privacy.txt


    local:
      - name: 'xndeye private adblock list'
        path: 'rule/private.txt'
        type: easylist

  output:
    file_header: |
      Title: xndeye adblock list ${type}
      Last Modified: ${date}
      Homepage: https://github.com/xndeye/adblock_list

    files:
      - name: easylist.txt
        type: easylist
        filter:
          - basic
          - wildcard
          - unknown

      - name: dns.txt
        type: easylist
        filter:
          - basic
          - wildcard

      - name: modify.txt
        type: easylist
        filter:
          - unknown

      - name: dnsmasq.conf
        type: dnsmasq

      - name: clash.yaml
        type: clash

      - name: smartdns.conf
        type: smartdns

      - name: hosts
        type: hosts
