# 参考 `application-example.yaml` 并在处添加订阅规则，请注意缩进
# Refer to `application-example.yaml` and add subscription rules there，please note the indentation

application:
  config:
    domain-detect:
      enable: false
      timeout: 10

  rule:
    remote:

      - name: AWAvenue-Adblock-Rule
        path: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/AdGuard/AdvertisingLite/AdvertisingLite.txt
        type: clash

      - name: dns-blocklists
        path: https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/pro.mini.txt
        type: easylist

      - name: 拦截所有中文广告
        path: https://raw.githubusercontent.com/fhvvbv/adblockfilters/refs/heads/main/rules/adblockdnslite.txt
        type: easylist

    local:
      - name: 'xndeye private adblock list'
        path: 'rule/private.txt'
        type: easylist

  output:
    file_header: |
      Title: xndeye adblock list ${type}
      Last Modified: ${date}
      Homepage: https://github.com/xndeye/adblock_list

    files:
      - name: easylist.txt
        type: easylist
        filter:
          - basic
          - wildcard
          - unknown

      - name: dns.txt
        type: easylist
        filter:
          - basic
          - wildcard

      - name: modify.txt
        type: easylist
        filter:
          - unknown

      - name: dnsmasq.conf
        type: dnsmasq

      - name: clash.yaml
        type: clash

      - name: smartdns.conf
        type: smartdns

      - name: hosts
        type: hosts
